---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demomicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demomicroservice
    spec:
      containers:
      - name: demomicroservice
        image: robertoh/demomicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: demomicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: demomicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demomicroservice
